---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/droplet.yml

- hosts: newdroplets
  user: root      
  vars_files:
    - vars.yml
  tasks:
    - wait_for: port=22 delay=10
    - include: tasks/users.yml
    - include: tasks/security.yml
    - include: tasks/software.yml
               
  handlers:
    - include: handlers/site.yml
